### PR TITLE
Add support for ESP32-C3

### PR DESCRIPTION
**Pull request by chrisbabcock**
This will allow target ESP32-C3 to compile with ESP32 r2.0.0-rc2.  I tested it on a ESP32-C3-DevKitM-1.

### CODE REVIEW

**Comment by pstolarz** [comment]
Thanks for pointing this out. I decided to use internal ESP SDK's `GPIO` struct instead of raw regs as in your PR, since this approach seems to be a little more generic. The ESP32-C3 fix is currently on [esp32_c](https://github.com/pstolarz/OneWireNg/tree/esp32_c) branch. Could you check if it works on your setup? (I'm not sure the `GPIO` struct is properly set in the ESP32-C3 cond. build - if not I'll change the code to raw regs as in your PR).

**Comment by chrisbabcock** [comment]
Yes, your change works for the registers.  There is a bug in the ESP32 Arduino core library, though, which causes the asserts to fire which you added for digitalPinIsValid and digitalPinCanOutput.  They left out initialization of esp32_gpioMux in esp32-hal-gpio.c for the ESP32-C3 specific target.  Removing the asserts was enough to verify functionality on the devkit.  I've filed a bug here: [https://github.com/espressif/arduino-esp32/issues/5613](https://github.com/espressif/arduino-esp32/issues/5613)

**Comment by pstolarz** [comment]
Looking at ESP32's `esp32-hal-gpio.c` I anticipated some kind of problem you noticed on your setup. It looks like for ESP32-C3 they use ESP-IDF's gpio lib instead of the Arduino's custom code (`USE_ESP_IDF_GPIO` is defined while `CONFIG_IDF_TARGET_ESP32C3` even if defined is in fact ignored)... At least Arduino's `GPIO` struct was mapped into the proper place of the reg-memory which is sufficient for the lib to work.

Could you check a new commit on `esp32_c` branch? It should fix the gpio validation assertion.

**Comment by chrisbabcock** [comment]
The updated validation works.

**Comment by pstolarz** [comment]
Fixed by #14

**Comment by mehulsharma21** [comment]
> Looking at ESP32's `esp32-hal-gpio.c` I'd been anticipating some kind of problem you noticed on your setup. It looks like for ESP32-C3 they use ESP-IDF's gpio lib instead of the Arduino's custom code (`USE_ESP_IDF_GPIO` is defined while `CONFIG_IDF_TARGET_ESP32C3` even if defined is in fact ignored)... At least Arduino's `GPIO` struct was mapped into the proper place of the reg-memory which is sufficient for the lib to work.
> 
> Could you check a new commit on `esp32_c` branch? It should fix the gpio validation assertion.

Hi, Please copy the below table and try.

#if CONFIG_IDF_TARGET_ESP32C3
    {0x04, -1,  0, -1},     // ADC1_CH0
    {0x08, -1,  1, -1},     // ADC1_CH1
    {0x0c, -1,  2, -1},     // ADC1_CH2 | FSPIQ
    {0x10, -1,  3, -1},     // ADC1_CH3
    {0x14, -1,  4, -1},     // MTMS | ADC1_CH4 | FSPIHD
    {0x18, -1,  5, -1},     // MTDI | ADC2_CH0 | FSPIWP
    {0x1c, -1, -1, -1},     // MTCK | FSPICLK
    {0x20, -1, -1, -1},     // MTDO | FSPID
    {0x24, -1, -1, -1},     //
    {0x28, -1, -1, -1},     //
    {0x2c, -1, -1, -1},     // FSPICSO
    {0x30, -1, -1, -1},     //
    {0x34, -1, -1, -1},     // SPIHD
    {0x38, -1, -1, -1},     // SPIWP
    {0x3c, -1, -1, -1},     // SPICSO
    {0x40, -1, -1, -1},     // SPICLK
    {0x44, -1, -1, -1},     // SPID
    {0x48, -1, -1, -1},     // SPIQ
    {0x4c, -1, -1, -1},     // USB-
    {0x50, -1, -1, -1},     // USB+
    {0x54, -1, -1, -1},     // U0RXD
    {0x58, -1, -1, -1},     // U0TXD

**Comment by pstolarz** [comment]
@mehulsharma21 This file is out of my control - it's part of ESP IDF, so please report the issue there. @chrisbabcock already reported this problem [here](https://github.com/espressif/arduino-esp32/issues/5613).

**Pull request closed without merging**
